modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="foody"
version="1.0.0"
displayName="Foody+"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="jonas, MCreator"

[[dependencies.foody]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



